/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.tiendaenlinea.integracion.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the catalogo table.
 */
public class CatalogoPk implements Serializable
{
	protected Integer idCatalogo;

	/** 
	 * Sets the value of idCatalogo
	 */
	public void setIdCatalogo(Integer idCatalogo)
	{
		this.idCatalogo = idCatalogo;
	}

	/** 
	 * Gets the value of idCatalogo
	 */
	public Integer getIdCatalogo()
	{
		return idCatalogo;
	}

	/**
	 * Method 'CatalogoPk'
	 * 
	 */
	public CatalogoPk()
	{
	}

	/**
	 * Method 'CatalogoPk'
	 * 
	 * @param idCatalogo
	 */
	public CatalogoPk(final Integer idCatalogo)
	{
		this.idCatalogo = idCatalogo;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof CatalogoPk)) {
			return false;
		}
		
		final CatalogoPk _cast = (CatalogoPk) _other;
		if (idCatalogo == null ? _cast.idCatalogo != idCatalogo : !idCatalogo.equals( _cast.idCatalogo )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (idCatalogo != null) {
			_hashCode = 29 * _hashCode + idCatalogo.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.tiendaenlinea.integracion.dto.CatalogoPk: " );
		ret.append( "idCatalogo=" + idCatalogo );
		return ret.toString();
	}

}
