/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.tiendaenlinea.integracion.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the categoria table.
 */
public class CategoriaPk implements Serializable
{
	protected Integer idCategoria;

	/** 
	 * Sets the value of idCategoria
	 */
	public void setIdCategoria(Integer idCategoria)
	{
		this.idCategoria = idCategoria;
	}

	/** 
	 * Gets the value of idCategoria
	 */
	public Integer getIdCategoria()
	{
		return idCategoria;
	}

	/**
	 * Method 'CategoriaPk'
	 * 
	 */
	public CategoriaPk()
	{
	}

	/**
	 * Method 'CategoriaPk'
	 * 
	 * @param idCategoria
	 */
	public CategoriaPk(final Integer idCategoria)
	{
		this.idCategoria = idCategoria;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof CategoriaPk)) {
			return false;
		}
		
		final CategoriaPk _cast = (CategoriaPk) _other;
		if (idCategoria == null ? _cast.idCategoria != idCategoria : !idCategoria.equals( _cast.idCategoria )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (idCategoria != null) {
			_hashCode = 29 * _hashCode + idCategoria.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.tiendaenlinea.integracion.dto.CategoriaPk: " );
		ret.append( "idCategoria=" + idCategoria );
		return ret.toString();
	}

}
