/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.tiendaenlinea.integracion.dto;

import edu.co.sena.tiendaenlinea.integracion.dao.*;
import edu.co.sena.tiendaenlinea.integracion.factory.*;
import edu.co.sena.tiendaenlinea.integracion.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class Factura implements Serializable
{
	/** 
	 * This attribute maps to the column idFactura in the factura table.
	 */
	protected Integer idFactura;

	/** 
	 * This attribute maps to the column fecha in the factura table.
	 */
	protected Date fecha;

	/** 
	 * This attribute maps to the column total in the factura table.
	 */
	protected Float total;

	/** 
	 * This attribute maps to the column Cuenta_tipoDocumento in the factura table.
	 */
	protected String cuentaTipodocumento;

	/** 
	 * This attribute maps to the column Cuenta_numeroDocumento in the factura table.
	 */
	protected String cuentaNumerodocumento;

	/**
	 * Method 'Factura'
	 * 
	 */
	public Factura()
	{
	}

	/**
	 * Method 'getIdFactura'
	 * 
	 * @return Integer
	 */
	public Integer getIdFactura()
	{
		return idFactura;
	}

	/**
	 * Method 'setIdFactura'
	 * 
	 * @param idFactura
	 */
	public void setIdFactura(Integer idFactura)
	{
		this.idFactura = idFactura;
	}

	/**
	 * Method 'getFecha'
	 * 
	 * @return Date
	 */
	public Date getFecha()
	{
		return fecha;
	}

	/**
	 * Method 'setFecha'
	 * 
	 * @param fecha
	 */
	public void setFecha(Date fecha)
	{
		this.fecha = fecha;
	}

	/**
	 * Method 'getTotal'
	 * 
	 * @return Float
	 */
	public Float getTotal()
	{
		return total;
	}

	/**
	 * Method 'setTotal'
	 * 
	 * @param total
	 */
	public void setTotal(Float total)
	{
		this.total = total;
	}

	/**
	 * Method 'getCuentaTipodocumento'
	 * 
	 * @return String
	 */
	public String getCuentaTipodocumento()
	{
		return cuentaTipodocumento;
	}

	/**
	 * Method 'setCuentaTipodocumento'
	 * 
	 * @param cuentaTipodocumento
	 */
	public void setCuentaTipodocumento(String cuentaTipodocumento)
	{
		this.cuentaTipodocumento = cuentaTipodocumento;
	}

	/**
	 * Method 'getCuentaNumerodocumento'
	 * 
	 * @return String
	 */
	public String getCuentaNumerodocumento()
	{
		return cuentaNumerodocumento;
	}

	/**
	 * Method 'setCuentaNumerodocumento'
	 * 
	 * @param cuentaNumerodocumento
	 */
	public void setCuentaNumerodocumento(String cuentaNumerodocumento)
	{
		this.cuentaNumerodocumento = cuentaNumerodocumento;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Factura)) {
			return false;
		}
		
		final Factura _cast = (Factura) _other;
		if (idFactura == null ? _cast.idFactura != idFactura : !idFactura.equals( _cast.idFactura )) {
			return false;
		}
		
		if (fecha == null ? _cast.fecha != fecha : !fecha.equals( _cast.fecha )) {
			return false;
		}
		
		if (total == null ? _cast.total != total : !total.equals( _cast.total )) {
			return false;
		}
		
		if (cuentaTipodocumento == null ? _cast.cuentaTipodocumento != cuentaTipodocumento : !cuentaTipodocumento.equals( _cast.cuentaTipodocumento )) {
			return false;
		}
		
		if (cuentaNumerodocumento == null ? _cast.cuentaNumerodocumento != cuentaNumerodocumento : !cuentaNumerodocumento.equals( _cast.cuentaNumerodocumento )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (idFactura != null) {
			_hashCode = 29 * _hashCode + idFactura.hashCode();
		}
		
		if (fecha != null) {
			_hashCode = 29 * _hashCode + fecha.hashCode();
		}
		
		if (total != null) {
			_hashCode = 29 * _hashCode + total.hashCode();
		}
		
		if (cuentaTipodocumento != null) {
			_hashCode = 29 * _hashCode + cuentaTipodocumento.hashCode();
		}
		
		if (cuentaNumerodocumento != null) {
			_hashCode = 29 * _hashCode + cuentaNumerodocumento.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return FacturaPk
	 */
	public FacturaPk createPk()
	{
		return new FacturaPk(idFactura);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.tiendaenlinea.integracion.dto.Factura: " );
		ret.append( "idFactura=" + idFactura );
		ret.append( ", fecha=" + fecha );
		ret.append( ", total=" + total );
		ret.append( ", cuentaTipodocumento=" + cuentaTipodocumento );
		ret.append( ", cuentaNumerodocumento=" + cuentaNumerodocumento );
		return ret.toString();
	}

}
