/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.tiendaenlinea.integracion.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the factura table.
 */
public class FacturaPk implements Serializable
{
	protected Integer idFactura;

	/** 
	 * Sets the value of idFactura
	 */
	public void setIdFactura(Integer idFactura)
	{
		this.idFactura = idFactura;
	}

	/** 
	 * Gets the value of idFactura
	 */
	public Integer getIdFactura()
	{
		return idFactura;
	}

	/**
	 * Method 'FacturaPk'
	 * 
	 */
	public FacturaPk()
	{
	}

	/**
	 * Method 'FacturaPk'
	 * 
	 * @param idFactura
	 */
	public FacturaPk(final Integer idFactura)
	{
		this.idFactura = idFactura;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof FacturaPk)) {
			return false;
		}
		
		final FacturaPk _cast = (FacturaPk) _other;
		if (idFactura == null ? _cast.idFactura != idFactura : !idFactura.equals( _cast.idFactura )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (idFactura != null) {
			_hashCode = 29 * _hashCode + idFactura.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.tiendaenlinea.integracion.dto.FacturaPk: " );
		ret.append( "idFactura=" + idFactura );
		return ret.toString();
	}

}
