/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.tiendaenlinea.integracion.dto;

import edu.co.sena.tiendaenlinea.integracion.dao.*;
import edu.co.sena.tiendaenlinea.integracion.factory.*;
import edu.co.sena.tiendaenlinea.integracion.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class ItemCarrito implements Serializable
{
	/** 
	 * This attribute maps to the column Producto_idProducto in the item_carrito table.
	 */
	protected String productoIdproducto;

	/** 
	 * This attribute maps to the column CarritoDeCompras_idCarritoDeCompras in the item_carrito table.
	 */
	protected String carritodecomprasIdcarritodecompras;

	/** 
	 * This attribute maps to the column cantidad in the item_carrito table.
	 */
	protected Integer cantidad;

	/** 
	 * This attribute maps to the column costoUnitario in the item_carrito table.
	 */
	protected Float costoUnitario;

	/** 
	 * This attribute maps to the column costoTotal in the item_carrito table.
	 */
	protected Float costoTotal;

	/**
	 * Method 'ItemCarrito'
	 * 
	 */
	public ItemCarrito()
	{
	}

	/**
	 * Method 'getProductoIdproducto'
	 * 
	 * @return String
	 */
	public String getProductoIdproducto()
	{
		return productoIdproducto;
	}

	/**
	 * Method 'setProductoIdproducto'
	 * 
	 * @param productoIdproducto
	 */
	public void setProductoIdproducto(String productoIdproducto)
	{
		this.productoIdproducto = productoIdproducto;
	}

	/**
	 * Method 'getCarritodecomprasIdcarritodecompras'
	 * 
	 * @return String
	 */
	public String getCarritodecomprasIdcarritodecompras()
	{
		return carritodecomprasIdcarritodecompras;
	}

	/**
	 * Method 'setCarritodecomprasIdcarritodecompras'
	 * 
	 * @param carritodecomprasIdcarritodecompras
	 */
	public void setCarritodecomprasIdcarritodecompras(String carritodecomprasIdcarritodecompras)
	{
		this.carritodecomprasIdcarritodecompras = carritodecomprasIdcarritodecompras;
	}

	/**
	 * Method 'getCantidad'
	 * 
	 * @return Integer
	 */
	public Integer getCantidad()
	{
		return cantidad;
	}

	/**
	 * Method 'setCantidad'
	 * 
	 * @param cantidad
	 */
	public void setCantidad(Integer cantidad)
	{
		this.cantidad = cantidad;
	}

	/**
	 * Method 'getCostoUnitario'
	 * 
	 * @return Float
	 */
	public Float getCostoUnitario()
	{
		return costoUnitario;
	}

	/**
	 * Method 'setCostoUnitario'
	 * 
	 * @param costoUnitario
	 */
	public void setCostoUnitario(Float costoUnitario)
	{
		this.costoUnitario = costoUnitario;
	}

	/**
	 * Method 'getCostoTotal'
	 * 
	 * @return Float
	 */
	public Float getCostoTotal()
	{
		return costoTotal;
	}

	/**
	 * Method 'setCostoTotal'
	 * 
	 * @param costoTotal
	 */
	public void setCostoTotal(Float costoTotal)
	{
		this.costoTotal = costoTotal;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof ItemCarrito)) {
			return false;
		}
		
		final ItemCarrito _cast = (ItemCarrito) _other;
		if (productoIdproducto == null ? _cast.productoIdproducto != productoIdproducto : !productoIdproducto.equals( _cast.productoIdproducto )) {
			return false;
		}
		
		if (carritodecomprasIdcarritodecompras == null ? _cast.carritodecomprasIdcarritodecompras != carritodecomprasIdcarritodecompras : !carritodecomprasIdcarritodecompras.equals( _cast.carritodecomprasIdcarritodecompras )) {
			return false;
		}
		
		if (cantidad == null ? _cast.cantidad != cantidad : !cantidad.equals( _cast.cantidad )) {
			return false;
		}
		
		if (costoUnitario == null ? _cast.costoUnitario != costoUnitario : !costoUnitario.equals( _cast.costoUnitario )) {
			return false;
		}
		
		if (costoTotal == null ? _cast.costoTotal != costoTotal : !costoTotal.equals( _cast.costoTotal )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (productoIdproducto != null) {
			_hashCode = 29 * _hashCode + productoIdproducto.hashCode();
		}
		
		if (carritodecomprasIdcarritodecompras != null) {
			_hashCode = 29 * _hashCode + carritodecomprasIdcarritodecompras.hashCode();
		}
		
		if (cantidad != null) {
			_hashCode = 29 * _hashCode + cantidad.hashCode();
		}
		
		if (costoUnitario != null) {
			_hashCode = 29 * _hashCode + costoUnitario.hashCode();
		}
		
		if (costoTotal != null) {
			_hashCode = 29 * _hashCode + costoTotal.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return ItemCarritoPk
	 */
	public ItemCarritoPk createPk()
	{
		return new ItemCarritoPk(productoIdproducto, carritodecomprasIdcarritodecompras);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.tiendaenlinea.integracion.dto.ItemCarrito: " );
		ret.append( "productoIdproducto=" + productoIdproducto );
		ret.append( ", carritodecomprasIdcarritodecompras=" + carritodecomprasIdcarritodecompras );
		ret.append( ", cantidad=" + cantidad );
		ret.append( ", costoUnitario=" + costoUnitario );
		ret.append( ", costoTotal=" + costoTotal );
		return ret.toString();
	}

}
